// Demo Data - Fake but realistic data for showcasing the system

export const demoSchools = [
  {
    id: 1,
    name: "Nairobi International School",
    email: "admin@nairobi-intl.edu",
    phone: "+254 712 345 678",
    address: "123 Westlands Road",
    city: "Nairobi",
    country: "Kenya",
    logo: "https://via.placeholder.com/150?text=NIS",
    principalName: "Dr. James Mwangi",
    registrationNumber: "REG-2020-001",
    studentCount: 1250,
    teacherCount: 85,
    totalRevenue: 4500000,
  },
  {
    id: 2,
    name: "Kampala Academy",
    email: "info@kampala-academy.ug",
    phone: "+256 701 234 567",
    address: "456 Kololo Hill",
    city: "Kampala",
    country: "Uganda",
    logo: "https://via.placeholder.com/150?text=KA",
    principalName: "Mrs. Grace Okello",
    registrationNumber: "REG-2019-002",
    studentCount: 890,
    teacherCount: 62,
    totalRevenue: 3200000,
  },
];

export const demoStudents = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Kariuki",
    email: "alice.kariuki@student.edu",
    phone: "+254 712 111 111",
    gender: "female",
    paymentCode: "STU-001-ABC123XYZ",
    admissionNumber: "ADM-2022-001",
    totalFeesRequired: 150000,
    totalPaid: 100000,
    balance: 50000,
    healthStatus: "Good",
    currentClass: "Form 4A",
    profilePhoto: "https://via.placeholder.com/200?text=Alice",
    admissionDate: "2022-01-15",
    subjects: ["Mathematics", "Physics", "Chemistry", "English"],
  },
  {
    id: 2,
    firstName: "James",
    lastName: "Omondi",
    email: "james.omondi@student.edu",
    phone: "+254 712 222 222",
    gender: "male",
    paymentCode: "STU-002-DEF456UVW",
    admissionNumber: "ADM-2022-002",
    totalFeesRequired: 150000,
    totalPaid: 150000,
    balance: 0,
    healthStatus: "Good",
    currentClass: "Form 4A",
    profilePhoto: "https://via.placeholder.com/200?text=James",
    admissionDate: "2022-01-15",
    subjects: ["Mathematics", "Biology", "Chemistry", "English"],
  },
  {
    id: 3,
    firstName: "Sarah",
    lastName: "Kipchoge",
    email: "sarah.kipchoge@student.edu",
    phone: "+254 712 333 333",
    gender: "female",
    paymentCode: "STU-003-GHI789RST",
    admissionNumber: "ADM-2022-003",
    totalFeesRequired: 150000,
    totalPaid: 75000,
    balance: 75000,
    healthStatus: "Excellent",
    currentClass: "Form 3B",
    profilePhoto: "https://via.placeholder.com/200?text=Sarah",
    admissionDate: "2023-01-20",
    subjects: ["Mathematics", "Physics", "English", "History"],
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Mwangi",
    email: "david.mwangi@student.edu",
    phone: "+254 712 444 444",
    gender: "male",
    paymentCode: "STU-004-JKL012MNO",
    admissionNumber: "ADM-2023-004",
    totalFeesRequired: 150000,
    totalPaid: 120000,
    balance: 30000,
    healthStatus: "Good",
    currentClass: "Form 2C",
    profilePhoto: "https://via.placeholder.com/200?text=David",
    admissionDate: "2023-09-01",
    subjects: ["Mathematics", "English", "Geography", "Biology"],
  },
  {
    id: 5,
    firstName: "Emily",
    lastName: "Njoroge",
    email: "emily.njoroge@student.edu",
    phone: "+254 712 555 555",
    gender: "female",
    paymentCode: "STU-005-PQR345STU",
    admissionNumber: "ADM-2023-005",
    totalFeesRequired: 150000,
    totalPaid: 90000,
    balance: 60000,
    healthStatus: "Good",
    currentClass: "Form 1D",
    profilePhoto: "https://via.placeholder.com/200?text=Emily",
    admissionDate: "2024-01-10",
    subjects: ["Mathematics", "English", "Science", "Social Studies"],
  },
];

export const demoTeachers = [
  {
    id: 1,
    firstName: "Mr.",
    lastName: "Peter Kipchoge",
    email: "peter.kipchoge@school.edu",
    phone: "+254 712 666 666",
    subjects: ["Mathematics", "Physics"],
    qualifications: "BSc Mathematics, MEd",
    employmentDate: "2015-08-01",
    classes: ["Form 4A", "Form 3B"],
  },
  {
    id: 2,
    firstName: "Ms.",
    lastName: "Jane Wanjiru",
    email: "jane.wanjiru@school.edu",
    phone: "+254 712 777 777",
    subjects: ["English", "Literature"],
    qualifications: "BA English, PGDE",
    employmentDate: "2018-01-15",
    classes: ["Form 4A", "Form 2C", "Form 1D"],
  },
  {
    id: 3,
    firstName: "Dr.",
    lastName: "Robert Mwangi",
    email: "robert.mwangi@school.edu",
    phone: "+254 712 888 888",
    subjects: ["Chemistry", "Biology"],
    qualifications: "BSc Chemistry, PhD",
    employmentDate: "2012-06-01",
    classes: ["Form 4A", "Form 3B"],
  },
  {
    id: 4,
    firstName: "Mr.",
    lastName: "Samuel Kiplagat",
    email: "samuel.kiplagat@school.edu",
    phone: "+254 712 999 999",
    subjects: ["History", "Geography"],
    qualifications: "BA History, PGDE",
    employmentDate: "2019-09-01",
    classes: ["Form 2C", "Form 1D"],
  },
];

export const demoPayments = [
  {
    id: 1,
    studentId: 1,
    studentName: "Alice Kariuki",
    paymentCode: "STU-001-ABC123XYZ",
    amount: 50000,
    paymentDate: "2024-01-15",
    paymentMethod: "Bank Transfer",
    referenceNumber: "BT-2024-001",
    status: "completed",
  },
  {
    id: 2,
    studentId: 1,
    studentName: "Alice Kariuki",
    paymentCode: "STU-001-ABC123XYZ",
    amount: 50000,
    paymentDate: "2024-02-20",
    paymentMethod: "Mobile Money",
    referenceNumber: "MM-2024-002",
    status: "completed",
  },
  {
    id: 3,
    studentId: 2,
    studentName: "James Omondi",
    paymentCode: "STU-002-DEF456UVW",
    amount: 75000,
    paymentDate: "2024-01-10",
    paymentMethod: "Bank Transfer",
    referenceNumber: "BT-2024-003",
    status: "completed",
  },
  {
    id: 4,
    studentId: 2,
    studentName: "James Omondi",
    paymentCode: "STU-002-DEF456UVW",
    amount: 75000,
    paymentDate: "2024-02-15",
    paymentMethod: "Bank Transfer",
    referenceNumber: "BT-2024-004",
    status: "completed",
  },
];

export const demoReceipts = [
  {
    id: 1,
    receiptNumber: "RCP-2024-001",
    studentName: "Alice Kariuki",
    paymentCode: "STU-001-ABC123XYZ",
    amountPaid: 50000,
    remainingBalance: 50000,
    paymentDate: "2024-01-15",
    schoolName: "Nairobi International School",
    schoolLogo: "https://via.placeholder.com/150?text=NIS",
  },
  {
    id: 2,
    receiptNumber: "RCP-2024-002",
    studentName: "Alice Kariuki",
    paymentCode: "STU-001-ABC123XYZ",
    amountPaid: 50000,
    remainingBalance: 0,
    paymentDate: "2024-02-20",
    schoolName: "Nairobi International School",
    schoolLogo: "https://via.placeholder.com/150?text=NIS",
  },
];

export const demoMarks = [
  {
    id: 1,
    studentId: 1,
    studentName: "Alice Kariuki",
    subject: "Mathematics",
    score: 85,
    grade: "A",
    exam: "Term 1 2024",
    remarks: "Excellent performance",
  },
  {
    id: 2,
    studentId: 1,
    studentName: "Alice Kariuki",
    subject: "Physics",
    score: 78,
    grade: "B+",
    exam: "Term 1 2024",
    remarks: "Good understanding of concepts",
  },
  {
    id: 3,
    studentId: 1,
    studentName: "Alice Kariuki",
    subject: "Chemistry",
    score: 82,
    grade: "A",
    exam: "Term 1 2024",
    remarks: "Strong in practical work",
  },
  {
    id: 4,
    studentId: 1,
    studentName: "Alice Kariuki",
    subject: "English",
    score: 88,
    grade: "A",
    exam: "Term 1 2024",
    remarks: "Excellent writing skills",
  },
  {
    id: 5,
    studentId: 2,
    studentName: "James Omondi",
    subject: "Mathematics",
    score: 92,
    grade: "A",
    exam: "Term 1 2024",
    remarks: "Outstanding performance",
  },
  {
    id: 6,
    studentId: 2,
    studentName: "James Omondi",
    subject: "Biology",
    score: 80,
    grade: "A",
    exam: "Term 1 2024",
    remarks: "Good grasp of topics",
  },
];

export const demoAccounts = {
  author: {
    id: 1,
    role: "author",
    firstName: "Admin",
    lastName: "Super",
    email: "admin@schoolmgmt.com",
    password: "demo123",
    schools: demoSchools,
  },
  schoolOwner: {
    id: 2,
    role: "school_owner",
    firstName: "Dr.",
    lastName: "James Mwangi",
    email: "principal@nairobi-intl.edu",
    password: "demo123",
    schoolId: 1,
    school: demoSchools[0],
  },
  teacher: {
    id: 3,
    role: "teacher",
    firstName: "Mr.",
    lastName: "Peter Kipchoge",
    email: "peter.kipchoge@school.edu",
    password: "demo123",
    schoolId: 1,
    teacherId: 1,
    classes: ["Form 4A", "Form 3B"],
    subjects: ["Mathematics", "Physics"],
  },
  student: {
    id: 4,
    role: "student",
    firstName: "Alice",
    lastName: "Kariuki",
    email: "alice.kariuki@student.edu",
    password: "demo123",
    schoolId: 1,
    studentId: 1,
  },
};

export const demoExams = [
  { id: 1, name: "Term 1 2024", year: 2024, term: 1, startDate: "2024-01-08", endDate: "2024-03-15" },
  { id: 2, name: "Term 2 2024", year: 2024, term: 2, startDate: "2024-04-01", endDate: "2024-06-15" },
  { id: 3, name: "Term 3 2024", year: 2024, term: 3, startDate: "2024-07-01", endDate: "2024-09-15" },
];

export const demoScholarships = [
  {
    id: 1,
    studentId: 3,
    studentName: "Sarah Kipchoge",
    type: "half",
    amount: 75000,
    status: "active",
    approvalDate: "2023-12-01",
  },
  {
    id: 2,
    studentId: 5,
    studentName: "Emily Njoroge",
    type: "custom",
    amount: 30000,
    status: "active",
    approvalDate: "2024-01-05",
  },
];

export const demoReports = {
  totalStudents: 5,
  totalTeachers: 4,
  totalRevenue: 435000,
  pendingPayments: 165000,
  averageAttendance: 94.5,
  averageGPA: 3.8,
};
